# ########### 各項插件設置 ############
settings:
  # 所有顯示的訊息均會有此前綴
  # 改了不代表可對外宣稱為您的自製插件
  plugin_prefix: '&7[&6LotteryItem&7]&r'
  # 輸入時間(單位:秒)
  # 打字不快的可以調高，或者複製貼上..
  input_time: 20

  
# ############ 抽獎清單敘述 ############
# 如果獎品是錢的物品名
type_money_name: '&6金錢'
# 機率顯示(單位:%)
# {chance}: 機率,可跟著獎品顯示一起設置
chance_display: '&8({chance}%)'
# 如果獎品是物品的顯示
# {item_name}: 物品名
# {amount}: 數量
# {chance_display}: 機率顯示
item_display: '&f{item_name} &r&f{amount} 個'
# 如果獎品是金錢的顯示
# {item_name}: 跟隨type_money_name
# {amount}: 數量
# {chance_display}: 機率顯示
money_display: '{item_name} &r&f{amount} 元'
# 鑰匙(需求)顯示
# {key}: 需求物(跟隨item_display, money_display格式)
key_display: '&7使用需求 [{key}&r&7]'
# 冷卻時間顯示(單位:秒)
# {seconds}: 秒數
cd_display: '&7（{seconds}秒冷卻）'
# 日期格式
# 格式設置錯誤會拋錯
# 詳細格式設置請google: SimpleDateFormat
date_format: 'yyyy年MM月dd日 HH:mm:ss'
# 使用期限顯示
# {date}: 日期
deadline_display: '&3{date} &7前可使用'
# 獎品排序方式
# 1: 機率由大至小排序
# 2: 機率由小至大排序
# 3: 由獎品名字排序
# 4: 先1再3
# 5: 先2再3
gifts_order: 4
# 獎品機率為100%的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_fixed_display: '{detail}'
# 獎品機率非100%的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_random_display: '{detail} &r&7[&6隨機&7]'
# 獎品為選擇的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_selectable_display: '{detail} &r&7[&3選擇&7]'
# 獎品明細敘述
# {gifts}: 所有獎品敘述的整合敘述(100%+非100%的組合)
# {cd_display}: 冷卻時間顯示(有設置才會顯示)
# {key_display}: 開啟需求顯示(有設置才會顯示)
# {deadline_display}: 使用期限顯示(有設置才會顯示)
gifts_lore:
- ''
- '&e&l獎勵 &r{cd_display}'
- '- {gifts}'
- ''
- '{key_display}'
- '{deadline_display}'
- '&7(&a右鍵使用&7)'


# ############ 抽獎訊息 ############
# saves.yml找不到此抽獎物ID時顯示
lotteryItem_not_available: '&c該抽獎物已無法使用。'
# 超過使用期限時顯示
lotteryItem_after_deadline: '&c該抽獎物已超過使用期限。'
# 冷卻時間尚未結束
# {seconds}: 冷卻秒數
lotteryItem_not_cooldown_yet: '&c該抽獎物尚未冷卻結束，剩餘 {seconds} 秒。'
# 需求物不足的顯示
lotteryItem_no_key: '&c缺少開啟需求物品。'
# 背包滿時東西噴到地上的顯示
inventory_full: '&c背包已滿，東西噴到了地上...'
# 是否啟用滑鼠顯示物品功能
show_item: false
# 消耗需求物品後的顯示訊息(若不想顯示請將此選項註解(#)掉)
# {key}: 鑰匙名稱
# {amount}: 數量
lotteryItem_consume_key: '&c消耗了&7[&f{key}&r&f × {amount}&7]&c。'
# 開啟抽獎物後顯示的訊息(若不想顯示請將此選項註解(#)掉)
# {li_name}: 抽獎物名稱
lotteryItem_use: '&c開啟{li_name}&r&c獲得了裡面的物品。'
# 獲得獎品訊息(安慰獎也算在獎品內；若不想顯示請將此選項註解(#)掉)
# {gift_name}: 獎品名字
# {amount}: 數量
lotteryItem_gift_get: '&a獲得了&7[&f{gift_name}&r&f × {amount}&7]。'
# 沒有獲得任何物品的訊息(若不想顯示請將此選項註解(#)掉)
lotteryItem_get_shit: '&c什麼也沒抽到...'
# 全頻廣播訊息
# {player}: 玩家名字
# {li_name}: 抽獎物名字
# {gift_name}: 獎品名字
# {amount}: 數量
lotteryItem_broadcast: '&a玩家&7<&f{player}&7>&a在&7[{li_name}&r&7]&a抽中了&7[&f{gift_name}&r&f × {amount}&7]&a。'