# ########### 各項插件設置 ############
settings:
  # 所有顯示的訊息均會有此前綴
  # 改了不代表可對外宣稱為您的自製插件
  plugin_prefix: '&7[&6LotteryItem&7]&r'
  # 輸入時間(單位:秒)
  # 打字不快的可以調高，或者複製貼上..
  input_time: 20

  
# ############ 抽獎清單敘述 ############
# 如果獎品是錢的物品名
type_money_name: '&6金錢'
# 機率顯示(單位:%)
# {chance}: 機率,可跟著獎品顯示一起設置
chance_display: '&8({chance}%)'
# 如果獎品是物品的顯示
# {item_name}: 物品名
# {amount}: 數量
# {chance_display}: 機率顯示
item_display: '&f{item_name} &r&f{amount} 個'
# 如果獎品是金錢的顯示
# {item_name}: 跟隨type_money_name
# {amount}: 數量
# {chance_display}: 機率顯示
money_display: '{item_name} &r&f{amount} 元'
# 鑰匙(需求)顯示
# {key}: 需求物(跟隨item_display, money_display格式)
key_display: '&7使用需求 [{key}&r&7]'
# 冷卻時間顯示(單位:秒)
# {seconds}: 秒數
cd_display: '&7（{seconds}秒冷卻）'
# 日期格式
# 格式設置錯誤會拋錯
# 詳細格式設置請google: SimpleDateFormat
date_format: 'yyyy年MM月dd日 HH:mm:ss'
# 使用期限顯示
# {date}: 日期
deadline_display: '&3{date} &7前可使用'
# 獎品排序方式
# 1: 機率由大至小排序
# 2: 機率由小至大排序
# 3: 由獎品名字排序
# 4: 先1再3
# 5: 先2再3
gifts_order: 4
# 獎品機率為100%的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_fixed_display: '{detail}'
# 獎品機率非100%的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_random_display: '{detail} &r&7[&6隨機&7]'
# 獎品為選擇的總顯示
# {detail}: 跟隨item_display, money_display格式
gift_selectable_display: '{detail} &r&7[&3選擇&7]'
# 獎品明細敘述
# {gifts}: 所有獎品敘述的整合敘述(100%+非100%的組合)
# {cd_display}: 冷卻時間顯示(有設置才會顯示)
# {key_display}: 開啟需求顯示(有設置才會顯示)
# {deadline_display}: 使用期限顯示(有設置才會顯示)
gifts_lore:
- ''
- '&e&l獎勵 &r{cd_display}'
- '- {gifts}'
- ''
- '{key_display}'
- '{deadline_display}'
- '&7(&a右鍵使用&7)'


# ############ 抽獎訊息 ############
# saves.yml找不到此抽獎物ID時顯示
lotteryItem_not_available: '&c該抽獎物已無法使用。'
# 超過使用期限時顯示
lotteryItem_after_deadline: '&c該抽獎物已超過使用期限。'
# 冷卻時間尚未結束
# {seconds}: 冷卻秒數
lotteryItem_not_cooldown_yet: '&c該抽獎物尚未冷卻結束，剩餘 {seconds} 秒。'
# 需求物不足的顯示
lotteryItem_no_key: '&c缺少開啟需求物品。'
# 背包滿時東西噴到地上的顯示
inventory_full: '&c背包已滿，東西噴到了地上...'
# 是否啟用滑鼠顯示物品功能
show_item: false
# 消耗需求物品後的顯示訊息(若不想顯示請將此選項註解(#)掉)
# {key}: 鑰匙名稱
# {amount}: 數量
lotteryItem_consume_key: '&c消耗了&7[&f{key}&r&f × {amount}&7]&c。'
# 開啟抽獎物後顯示的訊息(若不想顯示請將此選項註解(#)掉)
# {li_name}: 抽獎物名稱
lotteryItem_use: '&c開啟{li_name}&r&c獲得了裡面的物品。'
# 獲得獎品訊息(安慰獎也算在獎品內；若不想顯示請將此選項註解(#)掉)
# {gift_name}: 獎品名字
# {amount}: 數量
lotteryItem_gift_get: '&a獲得了&7[&f{gift_name}&r&f × {amount}&7]。'
# 沒有獲得任何物品的訊息(若不想顯示請將此選項註解(#)掉)
lotteryItem_get_shit: '&c什麼也沒抽到...'
# 全頻廣播訊息
# {player}: 玩家名字
# {li_name}: 抽獎物名字
# {gift_name}: 獎品名字
# {amount}: 數量
lotteryItem_broadcast: '&a玩家&7<&f{player}&7>&a在&7[{li_name}&r&7]&a抽中了&7[&f{gift_name}&r&f × {amount}&7]&a。'

# =========== GUI顯示 ===========
gui_create_title: 創建抽獎物
gui_edit_title: 編輯抽獎物
gui_edit_gift_title: 編輯獎品設置
gui_delete_gift_title: 確認刪除
gui_manager_title: 抽獎物管理介面
gui_selectable_gift_title: 請選擇一樣物品

button_show_id_name: '&6抽獎物唯一ID'
button_show_id_lore:
- '&7> &3{id}'

button_get_type_lore:
- ''
- '&7（拿著要抽取之物品點我一下）'

button_set_item_name_name: '&6設置抽獎物名稱&7[非必須]'
button_set_item_name_lore:
- '&7若不設置則會使用抽取物之物品名稱'
- '&7若想重置此設定請按&3&l中鍵'
- '&7目前設置: &f{name}:&d無（使用抽取物名稱）'

button_set_item_lore_name: '&6設置抽獎物敘述&7[非必須]'
button_set_item_lore_lore:
- '&7若不設置則會使用抽取物之物品敘述'
- '&7若想重置此設定請按&3&l中鍵'
- '&7換行符號（\n）'
- '&7目前設置: {lore}:&d無（使用抽取物敘述）'

button_set_consoprize_name: '&c未設置&7[非必須]'
button_set_consoprize_lore:
- ''
- '&d設置安慰獎（物品）'
- '&7拿著要設置為安慰獎的物品點我一下&a&l左鍵&r&7'
- '&c&l右鍵&r&7切換安慰獎型態'
- '&7若要移除安慰獎點我&3&l中鍵'
- '&7若不設置有可能會抽到空氣'
button_set_consoprize_name2: '&6金錢 {money} 元'
button_set_consoprize_lore2:
- ''
- '&d設置安慰獎（金錢）'
- '&a&l左鍵&r&7輸入'
- '&c&l右鍵&r&7切換安慰獎型態'
- '&7若要移除安慰獎點我&3&l中鍵'
- '&7若不設置有可能會抽到空氣'

button_set_key_name: '&c未設置&7[非必須]'
button_set_key_lore:
- ''
- '&d設置抽獎時的需求（物品）'
- '&7拿著要設置為需求的物品點我一下&a&l左鍵&r&7'
- '&c&l右鍵&r&7切換型態'
- '&7若要移除需求點我&3&l中鍵'
button_set_key_name2: '&6金錢 {money} 元'
button_set_key_lore2:
- ''
- '&d設置抽獎時的需求（金錢）'
- '&a&l左鍵&r&7輸入'
- '&c&l右鍵&r&7切換型態'
- '&7若要移除需求點我&3&l中鍵'

button_set_cd_name: '&6設置冷卻時間&7[非必須]'
button_set_cd_lore:
- '&7每隔幾秒可再次使用此抽獎物'
- '&7目前設置: &3{cd}'

button_set_period_of_use_name: '&6設置使用期限&7[非必須]'
button_set_period_of_use_lore:
- '&7超過此使用期限的抽獎物無法使用'
- '&7若輸入期限是過去式一樣無法使用'
- '&3&l中鍵&r&7取消使用期限'
- '&7輸入格式 &byyyy-MM-dd HH:mm:ss&7（24小時制）'
- '&7例: 1991-01-01 12:34:56'
- '&7目前設定: &3{date}:&d無'

button_set_sound_name: '&6設置抽獎音效&7[非必須]'
button_set_sound_lore:
- '&3&l中鍵&r&7取消使用音效'
- '&7輸入格式 &b聲音名稱(大小寫無關),音量,音調(音量音調≧0的小數)'
- '&7例: BLOCK_ANVIL_PLACE,1,1'
- '&7目前設定: &3{sound}:&d無'

button_set_add_gifts_lore_name: '&6是否添加獎品明細敘述'
button_set_add_gifts_lore_lore:
- '&7若不添加只會有原始物品的敘述'
- '&7- 添加（&a綠色羊毛&7）'
- '&7- 不添加（&c紅色羊毛&7）'

button_set_single_extract_name: '&6是否設置為單一抽取'
button_set_single_extract_lore:
- '&7單一抽取: 依獎品排序抽取獎品直到抽到1樣獎品為止'
- '&7(換言之此抽獎物只會抽到一個獎品(含安慰獎))'
- '&7- 設置（&a綠色羊毛&7）'
- '&7- 不設置（&c紅色羊毛&7）'

button_set_random_extract_name: '&6是否設置為隨機抽取'
button_set_random_extract_lore:
- '&7隨機抽取: 隨機從獎品中機率為100%的物品抽取一樣'
- '&7- 設置（&a綠色羊毛&7）'
- '&7- 不設置（&c紅色羊毛&7）'

button_set_selectable_name: '&6是否設置為選擇性抽獎'
button_set_selectable_lore:
- '&7玩家可從設置的獎品中任意選擇一樣(無關機率及不會廣播)'
- '&c&l**請注意若設置此項則"單一抽取"及"隨機抽取"會自動關閉且無法設置'
- '&7- 設置（&a綠色羊毛&7）'
- '&7- 不設置（&c紅色羊毛&7）'

button_notuse_name: '&8系統保留按鈕'

type_item_name: 物品
button_edit_gift_lore:
- ''
- '&7獎品型態: &3{type}'
- '&7獎品數量: &3{amount}'
- '&7中獎機率: &3{chance}％'
- '&7全服廣播: {broadcast}'
- ''
- '&d&l任意鍵&r&7編輯'
- '&a&lShift+右鍵&r&7刪除獎品'

button_create_new_gift_name: '&6新增獎品'

button_set_gift_type_name: '&6設置獎品型態（物品）'
button_set_gift_type_lore:
- ''
- '&7拿著要設置為獎品的物品點我一下&a&l左鍵&r&7'
- '&c&l右鍵&r&7切換型態（切換後會重置獎品數量）'
button_set_gift_type_name2: '&6設置獎品型態（金錢）'
button_set_gift_type_lore2:
- ''
- '&c&l右鍵&r&7切換型態（切換後會重置獎品數量）'

button_set_gift_amount_name: '&6設置獎品數量'
button_set_gift_amount_lore:
- '&7可設置單一數量或範圍數量'
- '&7若獎品為"物品"只可輸入整數'
- '&7範圍數量為從指定範圍中隨機選取數量'
- '&7範圍數量格式: &bmin-max&7（０＜min＜max）'
- '&7目前設定: &3{amount}:&d無'

button_set_gift_chance_name: '&6設置獎品中獎機率'
button_set_gift_chance_lore:
- '&7機率須符合規則：０＜機率≦１００（單位：百分比，可輸入小數）'
- '&c&l右鍵&r&7設定為"必定獲得"'
- '&7目前設定： &3{chance}:&c無'

button_set_gift_broadcast_name: '&6設置全服廣播'
button_set_gift_broadcast_lore:
- '&7抽中此獎品是否要全服廣播'
- '&7- 廣播（&a綠色羊毛&7）'
- '&7- 不廣播（&c紅色羊毛&7）'

button_confirm_name: '&a確認'
button_confirm_lore:
- '&7若要取消直接關閉頁面即可'

gifts_manager_display: '{item_display} &7[機率: {chance}] [是否廣播: {broadcast}&r&7]'
button_manager_lore:
- ''
- '&7- 抽獎物ID: &d{id}'
- '&7- 安慰獎: {conso_item}'
- '&7- 開啟需求: {key_item}'
- '&7- 冷卻: &d {seconds} &7秒'
- '&7- 使用期限: &d{date}'
- '&7- 抽獎音效: &d{sound}'
- '&7- 是否添加獎品明細: {addLore_symbol}'
- '&7- 是否單一抽取: {singleExtract_symbol}'
- '&7- 是否隨機抽取: {randomExtract_symbol}'
- '&7- 是否為選擇性獎品: {selectable_symbol}'
- '&7- 獎品明細:'
- ' {gifts}'
- ''
- '&a&l左鍵&r&7取得此抽獎物'
- '&9&l右鍵&r&7編輯此抽獎物'
- '&c&3Shift+右鍵&r&7刪除此抽獎物'
not_finished_yet_display: '&c======== 此抽獎物尚未完成編輯 ========'

button_create_li_name: '&6創建抽獎物'
button_create_li_lore:
- '&7點擊後輸入ID，不可與現有ID重複'

# =========== 各式訊息 ===========
message:
  LotteryItem_exists: '&c該抽獎物ID已存在。'
  LotteryItem_not_exists: '&c該ID之抽獎物不存在。'
  LotteryItem_removed: '&a抽獎物（{id}）已移除。'
  Input_notice: '&7請於 &c{seconds}&7 秒內完畢或輸入 &ccancel &7取消輸入。'
  Input_countdown: '&a目前正在輸入中，剩餘 &c{seconds} &a秒'
  Input_blocking: '&c您現在正在進行輸入，無法執行該動作。'
  Input_cancel: '&7已取消輸入。'
  Input_wrong: '&c輸入有誤。'
  Edit_finished: '&a抽獎物（{id}）已完成保存。'
  Not_finished_yet: '&c該抽獎物（{id}）尚未完成編輯，缺少：\n{reasons}' 
  No_permission: '&c你沒有權限使用此指令'
  Reload_successfully: '&a已重新讀取檔案。'
  Refresh_successfully: '&a已重製所有玩家身上的抽獎物'
  No_sound_name: '&c無此音效名稱。'
reason:
  No_name: '&7- 抽獎物名稱（抽取物無名稱）'
  No_lore: '&7- 抽獎物敘述（已關閉添加獎品明細敘述及抽取物無敘述）'
  No_gifts: '&7- 抽獎物獎品（沒有獎品）'
  
# ----------- 指令 -----------
cmd:
  Show_help:
  - ' &3/li create <ID> &7-創建抽獎物'
  - ' &3/li edit <ID> &7-編輯抽獎物'
  - ' &3/li remove <ID> &7-刪除抽獎物'
  - ' &3/li get <ID> [amount] &7-取得抽獎物'
  - ' &3/li manager(m) &7-抽獎物管理介面'
  - ' &3/li refresh &7-重製所有玩家身上的抽獎物'
  - ' &3/li reload [config|saves|items] &7-重新讀取檔案'
  Create_usage: '&cUsage: /li create <ID>'
  Edit_usage: '&cUsage: /li edit <ID>'
  Get_usage: '&cUsage: /li get <ID> [amount]'
  Remove_usage: '&cUsage: /li remove <ID>'
  Reload_usage: '&cUsage: /li reload [config|saves|items]'